export const colors = {
    "General Knowledge": "red",
    "Entertainment: Books": "brown",
    "Entertainment: Film": "pink",
    "Entertainment: Music": "pink",
    "Entertainment: Musicals & Theatres": "pink",
    "Entertainment: Television": "pink",
    "Entertainment: Video Games": "pink",
    "Entertainment: Board Games": "pink",
    "Science & Nature": "green",
    "Science: Computers": "green",
    "Science: Mathematics": "green",
    "Mythology": "brown",
    "Sports": "orange",
    "Geography": "blue",
    "History": "yellow",
    "Politics": "yellow",
    "Art": "brown",
    "Celebrities": "pink",
    "Animals": "red",
    "Vehicles": "red",
    "Entertainment: Comics": "pink",
    "Science: Gadgets": "green",
    "Entertainment: Japanese Anime & Manga": "pink",
    "Entertainment: Cartoon & Animations": "pink"
}